//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Draft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class possible_supply
    {
        public int ID { get; set; }
        public int Material_name { get; set; }
        public int Possible_supply1 { get; set; }
    
        public virtual materials materials { get; set; }
        public virtual supply supply { get; set; }
    }
}
