//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Draft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supply()
        {
            this.possible_supply = new HashSet<possible_supply>();
        }
    
        public int ID { get; set; }
        public string supply_name { get; set; }
        public int supply_type { get; set; }
        public string INN { get; set; }
        public int rating { get; set; }
        public string date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<possible_supply> possible_supply { get; set; }
        public virtual supply_type supply_type1 { get; set; }
    }
}
